<a href="https://colab.research.google.com/github/satwikbarik2-hub/Data-preprocessing/blob/main/np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)#1 row 5 column

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [ ]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("arrray:\n",arr)
print("shape:",arr.shape)
print("number of dimensions:",arr.ndim)
print("size :",arr.size)
print(arr.dtype)
print(arr.itemsize,"bytes")

arrray:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimensions: 2
size : 6
int64
8 bytes
